os: osx
osx_image: xcode9.4
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install:
  - gem install bundler || gem install bundler --version '< 2'
script: bundle exec rake spec_travis
gemfile: .travis.gemfile
before_script:
  - pg_ctl -D /usr/local/var/postgres start
  - createuser -s postgres
  - psql -c 'create database sequel_test;' -U postgres
services:
  - postgresql

notifications:
  email: false
