os: osx
osx_image: xcode9.4
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.2.0.0
before_install:
  - gem install bundler
script: bundle exec rake spec_travis
gemfile: .travis.gemfile
before_script:
  - pg_ctl -D /usr/local/var/postgres start
  - createuser -s postgres
  - psql -c 'create database sequel_test;' -U postgres
services:
  - postgresql
